import type { AnalysisResult } from "../state/appState.ts";

export interface TestResult {
  id: string;
  timestamp: string;
  sku: string;
  bottleName: string;
  imageName: string;
  totalVolumeMl?: number;
  analysisResult: AnalysisResult;
}

export function exportToJSON(results: TestResult[]): void {
  const dataStr = JSON.stringify(results, null, 2);
  const blob = new Blob([dataStr], { type: "application/json" });
  downloadBlob(blob, `afia-scans-${Date.now()}.json`);
}

export function exportToCSV(results: TestResult[]): void {
  const headers = [
    "Timestamp",
    "SKU",
    "Bottle Name",
    "Image Name",
    "Fill Percentage",
    "Remaining ML",
    "Consumed ML",
    "Confidence",
    "Scan ID",
  ];

  const rows = results.map((r) => [
    r.timestamp,
    r.sku,
    r.bottleName,
    r.imageName,
    r.analysisResult.fillPercentage.toString(),
    r.analysisResult.remainingMl?.toString() || "0",
    (r.totalVolumeMl ? r.totalVolumeMl - (r.analysisResult.remainingMl || 0) : 0).toString(),
    r.analysisResult.confidence,
    r.analysisResult.scanId,
  ]);

  const csvContent = [
    headers.join(","),
    ...rows.map((row) => row.map((cell) => `"${cell.replace(/"/g, '""')}"`).join(",")),
  ].join("\n");

  const blob = new Blob([csvContent], { type: "text/csv" });
  downloadBlob(blob, `afia-scans-${Date.now()}.csv`);
}

export function exportToPDF(results: TestResult[]): void {
  // Simple PDF generation using browser's print dialog
  const printWindow = window.open("", "_blank");
  if (!printWindow) {
    throw new Error("Popup blocked — allow popups to export PDF");
  }

  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>Afia Oil Tracker - Scan Report</title>
      <style>
        body { font-family: Arial, sans-serif; padding: 40px; }
        h1 { color: #2D6A4F; }
        .summary { margin: 20px 0; padding: 20px; background: #f5f5f5; border-radius: 8px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }
        th { background: #2D6A4F; color: white; }
        .footer { margin-top: 40px; padding-top: 20px; border-top: 2px solid #ddd; font-size: 12px; color: #666; }
      </style>
    </head>
    <body>
      <h1>🌻 Afia Oil Tracker - Scan Report</h1>
      <div class="summary">
        <strong>Report Generated:</strong> ${new Date().toLocaleDateString()}<br>
        <strong>Total Scans:</strong> ${results.length}
      </div>
      <table>
        <thead>
          <tr>
            <th>Date</th>
            <th>Bottle</th>
            <th>Fill %</th>
            <th>Remaining (ml)</th>
            <th>Confidence</th>
          </tr>
        </thead>
        <tbody>
          ${results.map(r => `
            <tr>
              <td>${new Date(r.timestamp).toLocaleDateString()}</td>
              <td>${r.bottleName}</td>
              <td>${r.analysisResult.fillPercentage}%</td>
              <td>${r.analysisResult.remainingMl || 0}</td>
              <td>${r.analysisResult.confidence}</td>
            </tr>
          `).join("")}
        </tbody>
      </table>
      <div class="footer">
        <p>Generated by Afia Oil Tracker on ${new Date().toLocaleString()}</p>
        <p>Results are estimates (±15%). Not certified nutritional analysis.</p>
      </div>
      <script>
        window.onload = function() {
          window.print();
          window.onafterprint = function() { window.close(); };
        };
      </script>
    </body>
    </html>
  `;

  printWindow.document.write(html);
  printWindow.document.close();
}

function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  // Defer revoke: some browsers need a tick to start the download before the URL is released
  setTimeout(() => URL.revokeObjectURL(url), 100);
}
